import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import { LogIn, LogOut, User } from "lucide-react";
import { getSession } from "@/lib/auth";
import { logout } from "@/app/actions/auth";
import "./globals.css";

// Inter font for body text (high‑performance sans‑serif)
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased font-sans bg-white text-black bg-grid-pattern min-h-screen flex flex-col`}
      >
        {/* Header – Ultra-minimal, sticky, backdrop blur */}
        <header className="sticky top-0 z-50 w-full border-b border-gray-200 bg-white">
          <div className="max-w-6xl mx-auto flex h-16 items-center justify-between px-4 sm:px-6 lg:px-8">
            <Link href="/" className="flex items-center gap-2 font-bold text-xl tracking-tight hover:opacity-80 transition-opacity">
              <div className="w-8 h-8 bg-black rounded-full flex items-center justify-center text-white">
                <span className="text-sm">R</span>
              </div>
              <span>RifaManía</span>
            </Link>
            <nav className="flex items-center gap-6 text-sm font-medium">
              {!session ? (
                <Link href="/login" className="text-gray-600 hover:text-black transition-colors flex items-center gap-2">
                  <LogIn className="w-4 h-4" />
                  <span>Iniciar Sesión</span>
                </Link>
              ) : (
                <>
                  <Link
                    href={session.role === 'admin' ? "/admin/rifas" : "/mis-inscripciones"}
                    className="text-gray-600 hover:text-black transition-colors flex items-center gap-2"
                  >
                    <User className="w-4 h-4" />
                    <span>{session.role === 'admin' ? 'Admin' : 'Mis Rifas'}</span>
                  </Link>
                  <form action={logout}>
                    <button type="submit" className="text-gray-600 hover:text-black transition-colors flex items-center gap-2">
                      <LogOut className="w-4 h-4" />
                      <span>Cerrar Sesión</span>
                    </button>
                  </form>
                </>
              )}
            </nav>
          </div>
        </header>

        {/* Main Content - Centered, spacious */}
        <main className="flex-1 w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          {children}
        </main>
      </body>
    </html>
  );
}
